### ISSUE TITLE
I'm working on an native Android application

### ISSUE THREAD

**Issue by letroll** [xbrowsersync/app#108]
Hello,

After tested the current Android application and see some issues:

- https://github.com/xbrowsersync/app/issues/53
- https://github.com/xbrowsersync/app/issues/78
- https://github.com/xbrowsersync/app/issues/47
- https://github.com/xbrowsersync/app/issues/29
- https://github.com/xbrowsersync/app/issues/25

I started working on a native application, and I would like to know if you are interested than I share my works

**Comment by nero120** [comment]
Hi @letroll, I've considered building a native app in the past, there's a couple of reasons why I decided to stick with Cordova but the main one is that having a unified code base means far less work to update all platforms. For now, the app is simple enough that it can share the code base with the extensions so I don't think there's a benefit in separating it out. Dev time is limited and must be utilised to complete implementation of core features before looking at nice to haves.

Regarding the issues:

- #47 will be resolved in v1.5.0 which I'm currently working on (#25 may also be resolved at this point).
- #53 cannot be resolved due to segregation of app data/no equivalent mobile api to web extensions.
- #29 will be resolved in future as part of the plan to support more services than just xBrowserSync services.

The interesting one is #78, this used to work but doesn't any more. It uses the cordova [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) plugin to open a hidden web view, load a url, then grab metadata from the loaded DOM before closing the web view. It relies on the [`loadstop` event listener](https://github.com/apache/cordova-plugin-inappbrowser#inappbrowseraddeventlistener) to fire once the url has finished loading but this no longer seems to work which is why xBrowserSync can no longer automatically populate bookmark metadata.

If you are able or willing to look into this issue then it would be a massive help! Otherwise no worries, if you still want to develop a native app then i'd be interested to see what you produce.

**Comment by vsatmydynipnet** [comment]
Hi, is there any progress? I miss my bookmarks on android alot. All Desktop is on 1.5 so Android can not read the bokmarks because of 1.4. Thank you

**Comment by nero120** [comment]
@vsatmydynipnet yes I'm making progress! I have been delayed in completing the release due to family commitments but hoping to get it out before xmas. Really sorry this has taken much longer than I'd hoped, bear with me.

**Comment by vsatmydynipnet** [comment]
sounds great to me! thank you very much. and we all do not have enough time for things we want to do. Love this solution!

**Comment by nero120** [comment]
Closing this as no longer relevant for this project.
