### ISSUE TITLE
Add a force upload/download button

### ISSUE THREAD

**Issue by maephisto666** [xbrowsersync/app#119]
**Is your feature request related to a problem?**
Linked to #118, I strongly believe that a button to explicitly trigger a download/upload of the bookmarks would really help.

I still remember that Xmarks (r.i.p.) had such functionality: I usually modify my bookmarks a lot, on different laptops, on different browsers, I sort them with SuperSorter on Chrome and this triggers an upload that now is always failing and I cannot find the root cause; you know, sync problems are always behind the corner, but if I strongly believe that my local copy is the "good" one, why not delegating to the end-user the ability to overwrite the remote bookmarks (force upload) or to overwrite the local bookmarks (force download)?

**Comment by nero120** [comment]
Hi @maephisto666, a number of points to this:

1. Sorting the bookmarks is causing an error which forces xBrowserSync to refresh your local bookmarks from the server (to prevent further issues). There's another [issue](https://github.com/xbrowsersync/app/issues/120) open which will track this.
2. You can always overwrite your current synced data by restoring from a backup file. This has the benefit of preserving descriptions and tags.
3. You can create a new sync which will be populated from the current local bookmarks, but descriptions and tags will be lost.

Since (1) is the main issue here I'll close this and that issue will be tracked in #120.

**Comment by Valinwolf** [comment]
I would still be nice to see a force upload/download option. I would also like to see the option to keep local or server when corruption is detected, though I suspect this won't be a problem when 1.6 hits the store page.

**Comment by kailiu42** [comment]
I too think that the force upload to and download from server buttons are necessary, and maybe it's better not to auto start syncing after first setup, but to offer the sync / force upload/ force download options.

Please consider this scenario: I was using whatever other means to sync my bookmarks cross browsers. Now after I've first setup xbrowsersync on my first browser, I'm going to setup it on my second browser, which already had some bookmarks from previous sync methods (maybe up to date with the data on my first browser, maybe not, doesn't matter). Now I'm not comfortable to just setup xbs on the second browser and let it auto start syncing without any choice, because I don't know what will happen nextL

Will the current bookmarks from the second browser be uploaded to overwrite my correct data from the first browser?
Will them be merged (then might create duplicated entries)?
Or will bookmarks be downloaded from the server?
Will the data left from previously sync method clutter up the xbs sync process thus delete my bookmarks?
My first browser is Firefox while the second is Chrome, thus will the difference confuse xbs on what bookmarks should be preserved and what need to be overwritten?

I don't know.

With the option to not auto start syncing and let me chose what to do I can force upload my data from first browser and force download on the second one. No unknown risks.

BTW, it's a nice software, thank you for making it. Just trying to make it better (at least better for my scenario).
