### ISSUE TITLE
Why do you hide the ability to uninstall? Not a good user experience

### ISSUE THREAD

**Issue by honeytrek** [xbrowsersync/app#121]
Please explain where I can uninstall, and WHY it is not obvious to the user. Do you want to "trick" users to keeping this on their system? I also checked the FAQ and the word uninstall was no where on the page. This is NOT how a company should opperate. Thanks for updating this and also telling the rest of us how to uninstall.

**Comment by nero120** [comment]
What are you talking about? xBrowserSync is a browser extension, you uninstall it like the millions of other extensions available. It is impossible to "hide the ability to uninstall" since the browser controls this. And since you deemed to include absolutely no useful information in your rant I don't know which browser you are using and so can't advise you further. Maybe you can complain to Google/Mozilla/etc.

And this is not a "company", you are using FOSS. I run this project in my spare time and do not get paid for it. Perhaps in future you should do more (read: some) investigation and due-dilligance before installing software on your devices...

**Comment by honeytrek** [comment]
Sorry you fealt attacked. I don't know what's a company or not. I just think you should have an uninstall option within the widget/plugin/etc. And it was popping up over my screen, so I had NO idea it was a browser add-on, as that wasn't mentioned anywhere that I saw in the options page.

**Comment by nero120** [comment]
You don't uninstall extensions from within the extension, you uninstall them from within the browser. Trust me, you don't want to be installing things you don't understand, you can change things inadvertantly or god-forbid, accidentally install something malicious that can compromise your system.
