### ISSUE TITLE
Brave Browser - "Something went wrong"

### ISSUE THREAD

**Issue by onemooresam** [xbrowsersync/app#127]
Auto and manual sync update (with changes pending) yields this message and no other information.

**Comment by onemooresam** [comment]
Sync worked on setup.  Bravesync is off.  Syncing between 2 instances of Brave and 2 instances of Chrome (1 each on MacOS Mojave and 1 each on MacOS Catalina)

**Comment by onemooresam** [comment]
These are occuring on the Mojave Mac.  Chrome is throwing the error, too.

**Comment by nero120** [comment]
Hey @onemooresam, can you paste the xBrowserSync log from the browser that is experiencing the issue?

**Comment by onemooresam** [comment]
[xBrowserSyncLog_20191025092355933.txt](https://github.com/xbrowsersync/app/files/3772263/xBrowserSyncLog_20191025092355933.txt)

**Comment by nero120** [comment]
@onemooresam it appears you have bookmarks with duplcate ids, not actually seen this error in the wild before!

Not sure what exactly would have caused it but to fix it, back up your bookmarks in xBrowserSync, open the backup file and find the bookmarks with ids 2 and 818. You'll need to change the ids manually so that each bookmark has a unique id. Find the highest id out of all of your bookmarks and update the duplicates with new ids that are higher than the highest id to avoid future conflicts. Once that's done, you can then restore this backup file which should fix the issue.

If you want to test it first, just create a new sync and restore to that to ensure it works correctly, then you can restore it back to your original sync ID.

**Comment by onemooresam** [comment]
Thanks, Rich.  I did as directed and get the following upon trying to restore: 
Connection lost
Couldn’t connect to the xBrowserSync service, check the service status in the Settings panel.

Upon checking status: Status: Online Version: 1.1.10

**Comment by nero120** [comment]
@onemooresam can you post the log file here please?

Also, would you be willing to send your back up file to admin@xbrowsersync.org so I can confirm it's valid?

**Comment by onemooresam** [comment]
@nero120 I set up a new sync using https://xbrowsersync.freerangecloud.com/ and it seems to be working. No error messages so far.

**Comment by nero120** [comment]
Ok then, glad to hear it's working. I'll close this but feel free to post any updates if required.
