### ISSUE TITLE
please can you compile version 1.5 for android?

### ISSUE THREAD

**Issue by sviluppoSoftware** [xbrowsersync/app#139]
if I read correctly the version 1.5 can also show the folders unlike version 1.4 which does not distinguish between bookmarks grouped in folders and those in the browser toolbar.
so I wanted to ask when the update will be available or at least the apk file for version 1.5 of the android app.
thnak you!

**Comment by nero120** [comment]
@sviluppoSoftware I am currently working on v1.5.1 which is mainly an update for Android and includes all of the v1.5.0 updates and more. It's taken longer than I'd hoped but I'm trying to get it out asap!

v1.5.0 doesn't include the folder view, I was planning on including it in v1.5.1 but I think I will have to push it to a future version otherwise it will take even longer to get v1.5.1 released.
