### ISSUE TITLE
Extension is not compatible with the last Brave versions (1.2.x)

### ISSUE THREAD

**Issue by LaurentOngaro** [xbrowsersync/app#150]
The brave browser team has recently changed the folder structure of their bookmarks.

This is a breaking change that make **all sync extensions unworkable**.

As the others, xbrowsersync is not working anymore and the sync process seems to run in an infinite loop after launched

The Brave team has been informed of this issue by several users, but I'm not sure they will revert the changes.

Perhaps,  xbrowsersync could make a fix for that, and become the FIRST sync extension compatible with the new versions of brave browser

**Comment by nero120** [comment]
Hi @LaurentOngaro, since xBrowserSync does not officially support Brave yet it's not a separate issue to be tracked, you can track implementation progress [here](https://github.com/xbrowsersync/app/issues/100).

However, unfortunately until Brave have implemented a workable solution I can't implemented support in xBrowserSync so I'll keep an eye [here](https://github.com/brave/brave-browser/issues/7639) and hopefully they'll come up with a way forward that keeps everyone happy.

**Comment by LaurentOngaro** [comment]
Hi @nero120 , thanks for your so quick answer. 
I understand your choice, and I disagree with those made by the Brave team (breaking backward compatibility). 
I hope they will fix this issue because Brave is really good on many points. 
If not, Vivaldi will be my alternative.

**Comment by nero120** [comment]
[This](https://github.com/brave/brave-browser/issues/7639#issuecomment-573259648) response from the big dog tells me they will sort it... 😉
