### ISSUE TITLE
Bug - Randomly missing most of the bookmarks on Android

### ISSUE THREAD

**Issue by cjnaz** [xBrowserSync/App#17]
On Android I've opened the App and found that most of my bookmarks (not all) are missing.  Setting > Data usage shows way low, so I believe they really are missing.  This has happened four times now over a couple weeks.  Perhaps an aborted download sync?  

### Steps to reproduce
1.  Open App on the Android device, and start to type in a search that should match.  Some bookmarks are there, but most are missing.  
2.  To resolve, force a new download sync by Settings > Disable Sync, then Sync button on the main page.  (the sync ID and encryption PW remain filled in).

If the issue is an aborted download, is there a download CRC to confirm a successful download?

### Client app information
**App Platform:**  
Standalone App on Android

**App Platform Version:** 
API version 1.1.0 on my own server.
App version 1.3.1

#### Other info
I'm running the API on my own server.  Never seen this problem on four other PCs with the Chrome browser extension of the App.

**Comment by nero120** [comment]
It's definitely not due to a transmission issue as the data is transmitted encrypted and decrypted at the client. If the data were corrupted in transit then it would not be possible to decrypt and you'd get an error displayed in the app.

If you close (by swiping it closed in the list of open apps) and re-open the app do all of your bookmarks re-appear?

**Comment by nero120** [comment]
@cjnaz are you still experiencing this issue?

**Comment by cjnaz** [comment]
No.  Consider it a sighting and go ahead and close it.
