### ISSUE TITLE
(Brave browser) All saved favicons always disappear in one of the two devices after syncing

### ISSUE THREAD

**Issue by garret** [xbrowsersync/app#184]
(Brave browser) All saved favicons disappear in one of the two devices after syncing

I am using the extension in two different laptops with Windows 10 and latest version of Brave (Version 1.8.86 Chromium: 81.0.4044.129). 

Syncing works flawlessly though, when I add a new bookmark in laptop 1, I notice it syncs with laptop 2 but this last one loses all the saved favicons in the bookmarks' toolbar. That is very annoying because, even when I click on the bookmark and the favicon is restored, the favicon will disappear again at the next sync. 

Do you know what is the issue and, eventually, how to fix it? 
Thank you very much in advance.

**Comment by nero120** [comment]
HI @garret, yes I'm aware of this and sadly there's no fix as such, as it's not really a bug. When xBrowserSync updates the local bookmarks it first has to clear the existing bookmarks (removing the favicons in the process), then it repopulates the local bookmarks from synced data. In order to then set the favicon for the bookmark you have to actually visit it again, it's not possible to do this via the API.

There is something I can do to mitigate this issue, which is to enhance the sync process to not clear the existing local bookmarks but to diff them against the synced data and only make necesary local changes. However, this is a major change and would take a lot of time, time which I just don't have and I'd rather put towards adding new functionality. Perhaps at some point in the future, sorry.

**Comment by garret** [comment]
Couldn't be at least added as a "feature request"?

**Comment by nero120** [comment]
@garret it's already on my backlog, no need to include it as a feature request.
