### ISSUE TITLE
Constant request to update, although it is already updated

### ISSUE THREAD

**Issue by xDonatello** [xbrowsersync/app#192]
The latest version available for the Google Chrome extension is 1.5.2
However, having released 1.5.2.1 (only the Source Code), every time I open Google Chrome it warns me that a new version is available. In fact, if I click, nothing happens.
The same thing happens on Firefox, Edge and on the Android app.
This thing is very annoying. Thanks for your time.

![image](https://user-images.githubusercontent.com/13498803/81582017-cf051c80-93af-11ea-9cc4-8d9de547a66a.png)

**Comment by nero120** [comment]
@xDonatello I am aware of this and realise it's annoying. It's due to the ongoing efforts to resolve the issues with [F-Droid](https://github.com/xbrowsersync/app/issues/165).

Since they build the app from source by taking the latest release source code from GitHub, to build with necessary android fixes they needed a new release which is the reason why everyone is getting an alert for a new version. This release is not relevant to other platforms but I have no way of stopping the alert. 😢 

Hopefully the F-Droid issues will be resolved soon and I can delete the release and stop the alerts.

**Comment by nero120** [comment]
I've deleted the release that was causing the issue.
