### ISSUE TITLE
Local HTML file that can be rendered as a homepage for any browser on Android

### ISSUE THREAD

**Issue by danorul9** [xbrowsersync/app#195]
Would you be able to add a local .html file android once the sync is setup?

This that case I can point my home page on any browser to access this file.  I would appreciate 2 main features on this page adjust font size and search.

**Comment by cjnaz** [comment]
Plus 1.

I offer this functional prototype, produced from [xbsjsonedit](https://github.com/cjnaz/xbsjsonedit).  Run the tool with the `--html <outfile.html>` switch.  It outputs a web page of tagged bookmarks, which can be opened in any desktop or android browser.

My usage of this file is to open it and use it as the launch page for my bookmarked pages.  Clicking on a bookmark link opens a new tab.

This xbsjsonedit solution is a lacking because 1) it is not dynamic (it operates on a xBrowserSync backup file), and 2) in order for the file to be visible outside the LAN it would have to be pushed to a internet visible server, which defeats the key privacy goal of the xBrowserSync project.  

Again, I bump the feature request.  I propose a button in the xBrowserSync API that on-demand generates and opens the web page.  The page should probably be auto-refreshed when bookmarks are added or touched, or have a refresh button.  It should probably support non-tagged bookmarks, and probably represent the hierarchy of the bookmark bar folders.

**Comment by cjnaz** [comment]
Example output from xbsjonedit (stripped down, rename to .html)...

[tagslist.txt](https://github.com/xbrowsersync/app/files/4753684/tagslist.txt)

**Comment by nero120** [comment]
@danorul9 this functionality is partly covered by #167, however it won't be a local file but a web-based version of the app. At this time I consider any other way of xBrowserSync displaying bookmarks to be duplicated functionality so I do not intend to implement other solutions to the same problems already solved.

**Comment by nero120** [comment]
@cjnaz I appreciate the effort, however as I mention above I consider this to be duplicate functionality and since I have [much work to do](https://github.com/xbrowsersync/app/wiki/Roadmap) until v1 is considered feature complete I simply don't have time to consider alternatives at this point.

As you've already alluded, #167 will allow you to make xBrowserSync the home page of your browser so hopefully that will suffice.

**Comment by cjnaz** [comment]
Hi Rich, thanks again for all your work on this.
I was looking for some specifics on your directions for this, such as...
- Do the Firefox and Chrome plugins go away?
- What's the planned view and functionality of the web app?
- Security sounds like a new challenge since the server would be supporting numerous simultaneous users with their data unencrypted.

Do you have a design discussion page for this phase of the project?  Perhaps my prototype page can help the discussion.
As an aside, I'll submit a feature request for periodic scheduled backups from the App, if that's a good way to get them in additional to manually mashing the Backup button.

**Comment by nero120** [comment]
> Do the Firefox and Chrome plugins go away?

Not at all, the web app is simply treated as another platform (alongside chrome, firefox and android).

> What's the planned view and functionality of the web app?

It will be essentially identical to the android app, except without the hardware api integrations and hosted via the web.

> Security sounds like a new challenge since the server would be supporting numerous simultaneous users with their data unencrypted.

All user data is stored on the web already since all xBrowserSync services are connected to the web so you can access them. All data on services is stored in encrypted form, the web app would not change this. Any cached data the web app used is stored locally on the client and is never transmitted.

> Do you have a design discussion page for this phase of the project? Perhaps my prototype page can help the discussion.

The xBrowserSync [Patreon](https://www.patreon.com/xbrowsersync) page is probably the most suitable place for general feature discussion if the goal is to best influence my thinking. Otherwise I'm always open to ideads posted in github but no guarantees that I'll implement them.

> As an aside, I'll submit a feature request for periodic scheduled backups from the App, if that's a good way to get them in additional to manually mashing the Backup button.

#15 😄
