### ISSUE TITLE
Resume syncing should NOT delete local bookmarks but really update them with remote storage

### ISSUE THREAD

**Issue by pstein** [xbrowsersync/app#252]
We are here evaluating xBrowsersync.

A few weeks ago I disabled xBrowserSync AddOn by clicking on "Disable" button (in newest Firefox).
In the meantime some bookmarks were deleted others added.

Yesterday I tried to resume syncing again (with the same server).
So I clicked on "sync" button and entered previous Password.
Much to my surprise I am prompted:

"Are you sure? xBrowserSync will delete all local bookmarks data before restoring synced bookmarks. OK to proceed?"

Why are all local bookmarks deleted?

I expected that new local bookmarks are added to remote storage and new, local deleted bookmarks are removed from remote storage.

So how do we achieve this?

**Comment by nero120** [comment]
Local bookmarks are deleted when re-activating sync in order to ensure that local bookmarks structure is identical to synced bookmarks structure. To achieve this without deleting everything first xBrowserSync would need to detect differences and then prompt the user for action - merge or replace. There is already an issue open for [merge](https://github.com/xbrowsersync/app/issues/194).
