### ISSUE TITLE
How to delete saved bookmarks on server without syncing?

### ISSUE THREAD

**Issue by pstein** [xbrowsersync/app#267]
Assume I synced a while my bookmarks with a certain xbrowsersync server.

Now I decide to stop syncing (with this server).
To feel better I would like to remove all my stuff which is currently stored on that server.

How can I do this WITHOUT prior syncing?

I miss an option "empty store on server without sync before" or similar

How can I achieve this?

**Comment by nero120** [comment]
This is a bit redundant since the whole point of xBrowserSync is to securely sync your data - which is encrypted locally. No one can decrypt your data except for you, unless they find a way to break AES encryption in which case we're all in trouble! I understand that it might make you feel better to have this as an option but in reality it's more practical to trust the encryption is secure that the person running the service! In any case, most people just email me (if they are synced to api.xbrowsersync.org) and I delete their sync for them (which is also a bit pointless since any unused sync is deleted automatically in three weeks!).
