### ISSUE TITLE
Add Firefox for Android (Fenix) support

### ISSUE THREAD

**Issue by rodrigoswz** [xbrowsersync/app#272]
**Is your feature request related to a problem?**

Yes, there is already a way to add non-approving addons by Mozilla on Firefox Nightly for Android, but unfortunately xBrowserSync is one of the addons that even installing does not really work.

After installing and log in with your credentials, an error occurs and sync bookmarks doesn't happen.

**Tell us about your idea**

Add support for the new mobile version of Firefox, this would be great because the bookmarks would be available within the browser without the need to use a second app for this.

More info: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by SimonBrazell** [comment]
I can confirm the extension does not work on the latest Firefox for Android (Fenix).

**Comment by Tarnyko** [comment]
I second this.
The extensions installs and accepts the SyncID/password couple, but freezes on the "Syncing" progression window.
![screen](https://user-images.githubusercontent.com/3727259/110714859-76d3bc80-8204-11eb-8d38-c12ee17f90db.jpg)

**Comment by nero120** [comment]
[Firefox for Android does not fully support the web extensions APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#bookmarks). Syncing to mobile browsers is not supported due to the effort involved in implementing this functionality, as such the android app was developed as a compromise that would at least allow users to access their synced data on their mobile device.

**Comment by rokejulianlockhart** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1625231
