### ISSUE TITLE
Syncing settings and extensions

### ISSUE THREAD

**Issue by manwe-pl** [xbrowsersync/app#289]
Just found this extension, looks really promising. But besides bookmarks, tabs and history, I think syncing settings and extensions is important. Now with Chromium if I add extension on one PC, it gets downloaded on the second one as soon as I turn on the browser there. Same thing with browser's settings, like theme. It would be great to have this feature in xBrowserSync. Especially now when Google (being usual assholes) is killing sync feature for Chromium.

**Comment by nero120** [comment]
Hi @manwe-pl, thanks for the suggestion. Since xBrowserSync is intended to run on multiple browsers that are not necessarily compatible, it is incredibly difficult to sync settings/extensions between those - if indeed the web extensions API even supports retrieving/updating those settings. For now, the [roadmap](https://github.com/xbrowsersync/app/wiki/Roadmap) includes syncing bookmarks, history and open tabs and that seems achievable. xBrowserSync was not intended to be a complete replacement for native syncing solutions to keep it lightweight and easy to maintain (even as it is it is a very complex codebase!). I'm sorry to say that for the foreseeable future I don't think syncing settings/extensions is feasible.
