### ISSUE TITLE
Edge Icon Only feature being ignored

### ISSUE THREAD

**Issue by BadCoder12** [xbrowsersync/app#296]
On Edge's bookmark toolbar, you can right click a bookmark and select "Show icon only" when you create/delete a new bookmark and it syncs, it reloads all the bookmarks but this settings is missing so it shows the title again.

**How can the issue be reproduced?**
Create new bookmark in Edge on the bookmark toolbar, right-click it and select "Show icon only"
On the phone create a new bookmark and when Edge syncs it will show the title of the bookmark again

**Desktop browser**
Please complete the following information for all affected desktop browsers:

- OS: Windows
- Browser Edge
- Version  90.0.818.46

**Mobile device**
Any Android

**Application log**
Please include the logs from the affected clients:

**Comment by nero120** [comment]
@BadCoder12 this is because currently, when xBrowserSync detected there are sync changes on the service, it has to delete all local bookmarks before pulling changes and recreating all bookmarks. There is a feature request to merge changes (194) instead of deleting and recreating, once that's been implemented then this issue will be resolved.
