### ISSUE TITLE
Selective sync option?

### ISSUE THREAD

**Issue by orschiro** [xBrowserSync/App#3]
Dear @nero120,

Remembering https://github.com/xBrowserSync/App/issues/1, how about an option to specify the root bookmark folder to sync? :-)

Yours,

Robert

**Comment by orschiro** [comment]
Alright, that sounds great!

Let me know whenever I can help :-)

**Comment by orschiro** [comment]
Any news on this, @nero120? :-)

**Comment by nero120** [comment]
In the process of adding Firefox support for the next release, so no progress on this request as yet. After thinking about it over the last few days, it does seem a bit counterproductive to implement a complex feature like this when the real issue is due to the limit on free sync space.

This could be solved much more easily by upping the limit to 5MB per sync (currently 500KB), but then the app would not be able to support many free users (the server/disk usage is not free and currently I eat the cost). Perhaps a better compromise would be to offer a paid option if you'd like to have a bigger sync size?

**Comment by orschiro** [comment]
> Perhaps a better compromise would be to offer a paid option if you'd like to have a bigger sync size?

Like the idea! How much would that be, roughly?

**Comment by nero120** [comment]
Good question! Let me have a think about how I'd implement it and check the hosting costs and get back to you.

**Comment by nero120** [comment]
Right @orschiro, how about this. $1 (USD) / month for a maximum sync size of 1GB. Subscription will be via [Patreon](https://www.patreon.com/) (I'll create an xBrowserSync Patreon account) to save me having to manage accounts/payments. There will be some caveats however:

- The subscription will be per sync ID (easier to manage max sync size for a given ID)
- This will obviously affect anonymity aspects of the service, though I will still endeavour not to store any personal information within the xBrowserSync system. Your personal/payment data will be stored on Patreon along with the sync ID you are using, and xbs will check subscription data via Patreon's APIs (I still need to confirm exactly how this will work but I think it's possible in theory).

Providing this functionality will take a bit of time for me to build but I'll aim to release it along with the Firefox support in the upcoming release.

What do you think?

**Comment by orschiro** [comment]
Sounds good to me! Shall we share the link to this issue thread to Reddit
and the like to get a feeling for how many people would support such a
Patreon campaign?

**Comment by nero120** [comment]
Ok great! If you'd like to post this on Reddit please go ahead. Xbs only has a small user base but it's growing steadily.

-------- Original Message --------

**Comment by orschiro** [comment]
@nero120 can you respond to this?

https://www.reddit.com/r/opensource/comments/75nhbn/who_wants_to_support_an_open_source_web_browser/do81jef/

**Comment by orschiro** [comment]
Hey Rich.

That sounds good to me. Maybe the target group for this is actually fine
setting up their own server.

Right now I'm not interested doing so but may consider that for the future!

**Comment by nero120** [comment]
Ok no problem @orschiro, sorry I couldn't be of more help at this time. I'll close this issue now.

**Comment by orschiro** [comment]
Absolutely no problem. You helped a lot already ☺

**Comment by Shadowpheonix** [comment]
I too would _**really**_ like this feature.  I am successfully running my own XBrowserSync server, so the storage space is not an issue for me.
In my case, I essentially have 3 sets of bookmarks that I am trying to sync - my "work" bookmarks, my "personal" bookmarks, and my "shared" bookmarks. I have 2 devices which need all 3 sets on them, 2 devices that need the "work" and "shared" bookmarks, and 3 devices that need "personal" and "shared". 
I used to be able to do this perfectly with XMarks, which as you know recently shut down.  Since then, I have switched to XBrowserSync, but have to use different profiles for each group of systems and manually copy links between the different bookmark sets (meaning I have to copy the links manually 2 or 3 times instead of 4 to 7).

**Comment by nero120** [comment]
Hi @Shadowpheonix, since this thread is tracking an old issue more related to the data limit, could I ask you to open a new issue for tracking your request and detail exactly what functionality you would like added? That way I can properly assess what's needed and gauge popularity better when picking up new features to implement. Thanks! 😄
