### ISSUE TITLE
Provide .xpi for firefox

### ISSUE THREAD

**Issue by ltlnx** [xbrowsersync/app#304]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is:

In the 1.6.0 pre-release, there is a zip provided for Firefox, but when selecting it to install, Firefox throws me an error
<img width="374" alt="螢幕快照 2021-05-23 下午4 54 59" src="https://user-images.githubusercontent.com/52026741/119254216-98f29f00-bba4-11eb-9417-3e698572c6dc.png">
And there is not much relevant info about installing zips in Firefox. Most websites pointed to the xpi packaging format.

**Tell us about your idea**
Could you include xpi files? TIA.

**Comment by nero120** [comment]
Installing add-ons using a .xpi file requires that the add-on be signed by Mozilla, otherwise Firefox will not allow you to install them. Pre-releases are not signed, so the only way to install the pre-release Firefox .zip file is to browse to `about:debugging#/runtime/this-firefox`, click on "Load Temporary Add-on...", then select the .zip file. This will run the add-on until you close Firefox, you'll have to follow the same process to reload the add-on after you open Firefox again.
