### ISSUE TITLE
Support and sync Chrome/Brave's Other and Mobile bookmarks

### ISSUE THREAD

**Issue by andbenn** [xbrowsersync/app#334]
In use:
- xBrowserSync addon - V1.5.2 in Brave and Firefox
- Android - V1.5.2

Chrome and Brave (maybe other Chromium based browsers as well) have the notion of Mobile and Other bookmark collections in addtion to the Toolbar bookmarks.

Please consider syncing these Mobile and Other bookmark folders when present.  Also the mobile apps may need updates to handle these other hierarchies.

One concern to consider, is that if bookmarks would be in these folders, how they would show up in other browsers that don't have these hierarchies, such as desktop Firefox.

**Comment by olavinto** [comment]
Chromium based mobile browsers do not support addons, including Google Chrome so that might be rather difficult to accomplish unless it would be possible to edit the bookmark storage files directly (I have no idea if that would be possible). Firefox on the other hand has official support for extension on Android at least although the list of supported addons is still very limited (only selected addons are included and they can be installed from the list that is included in Firefox). I would take Firefox sync though because it is my primary browser on all platforms.

**Comment by andbenn** [comment]
Chrome/Brave appears to put Mobile bookmarks at the same level in the bookmark hierarchy as desktop bookmarks.  You'll see this in the Bookmark Manager.  Mine is "Bookmarks", "Other bookmarks", and "Mobile Bookmarks" in brave.

Currently xbrowsersync doesn't pick up these mobile bookmarks for syncing when syncing from the desktop.

My ask isn't to support mobile browsers, but to consider all the bookmarks that Chrome/Brave and Firefox desktop may hold between desktops and mobile.

Hope that clarifies.

**Comment by olavinto** [comment]
Yep, sorry, it did! 🙂

**Comment by nero120** [comment]
@andbenn xBrowserSync syncs "Other bookmarks" and "Bookmarks bar" in Chrome/Brave, and "Other bookmarks", "Bookmarks Toolbar" and "Bookmarks Menu" in Firefox. Prior to v1.6.0, it also synced "Mobile Bookmarks" in Firefox but this has been removed in v1.6.0.

The reason I do not want to sync Mobile bookmarks is that the container is not present in either browser by default, only appearing once you have enabled their propriatary sync. Secondly, it is already the case that enabling both xBrowserSync and other syncing tools can cause sync issues so you cannot have both, choose one or the other. The fact that xBrowserSync was syncing Mobile bookmarks in Firefox struck me as inconsistent with this requirement so I have removed it.
