### ISSUE TITLE
1.6.0-beta.22 Restore Backup not working in Chrome, works in Firefox.

### ISSUE THREAD

**Issue by kainz** [xbrowsersync/app#352]
Linux 1.6.0-beta.22 'Restore from Backup' only working in some browsers

In a fresh browser profile, install the matching 1.6.0-beta.22 xbrowsersync browser extension.

- OS: Ubuntu 21.04
- Browser: Chrome, Firefox
- Version: Chrome 95.0.4638.69 (Official Build) (64-bit), Firefox 93.0

Nothing indicative of the restore process querying or starting is present in the Chrome xbs log, the Firefox xbs restore backup appears to work normally, using a xbs backup created from the XBS 1.5.2 chrome extension.

**Comment by nero120** [comment]
Just recreated on Ubuntu 20.04.3 LTS. The browser closes the extension window when you select the backup file which is the same behaviour as Firefox. Very annoying! I would like to provide the file select rather than users having to copy/paste backup data but obviously it doesn't work at the moment so I might need to revert back to the copy/paste. I'll have a think.

**Comment by kainz** [comment]
(p.s. missed a typo, my repro was 21.04)

**Comment by nero120** [comment]
Couldn't find a workaround so I had to revert back to using the textarea to paste backup data for chromium when running on linux.
