### ISSUE TITLE
1.6.0 beta 24 does not accept a sync upgraded with a previous beta version

### ISSUE THREAD

**Issue by olavinto** [xbrowsersync/app#354]
**Describe the issue you are experiencing**
1.6.0 beta 24 does not accept a sync upgraded with a previous beta.

**How can the issue be reproduced?**
I installed the extension (nice that this time it can actually be installed as a permanent addon, for the Nightly version of Firefox anyway) and when I try to log in it gives the following error: "This ID cannot be synced with this version of xBrowserSync as the sync has been upgraded to a later version.".

**Desktop browser**
- OS: Windows 11 Dev-channel
- Browser: Firefox Nightly
- Version: 1.6.0 beta 24

**Comment by nero120** [comment]
Doh! Sorry @olavinto, I'll get this sorted today.

**Comment by olavinto** [comment]
Well that was the quickest bug fix ever. 👍

**Comment by nero120** [comment]
Try this: https://github.com/xbrowsersync/app/releases/tag/v1.6.0-beta.25

**Comment by olavinto** [comment]
Yep, seems to work now. Thanks!

**Comment by nero120** [comment]
Great stuff, thanks for confirming!

**Comment by olavinto** [comment]
Still does not log in on Edge though and gives this error: "If the problem persists please report the issue.". It syncs fine when you click log in but then reverts to signed out state with the error. This has been the case for all the betas I've tried. Chrome works just fine.

**Comment by nero120** [comment]
@olavinto I get no issue when using beta 25 in Edge v96 - can you upload your edge log here please?

**Comment by olavinto** [comment]
[92ee1939-4ab0-4206-8ecd-ea159b739bbc.txt](https://github.com/xbrowsersync/app/files/7625888/92ee1939-4ab0-4206-8ecd-ea159b739bbc.txt)

**Comment by nero120** [comment]
Interesting, I'm not sure that's a bug specifically with edge, since it's occurring in `buildIdMappings` which takes bookmarks from sync data (not browser-specific) and it's hitting an issue whilst processing them. I've not seen this before. Is there any chance you can provide me with a backup file so I can try to replicate this? If you don't want to post it here you can email it to me at admin@xbrowsersync.org.

**Comment by olavinto** [comment]
I figured it out. My 'separators' are the culprit. I use these https://bookmarkseparators.com/?i=chrome on my toolbar to 'group' bookmarks and Edge does not like duplicates in a folder and always wants to remove all copies. Once I deleted all of those xBrowserSync stayed logged in. Funnily enough I restored them from a backup and now the addon gives the error again but it stays logged in and syncs. I have actually sent feedback to Microsoft about the removal of duplicates some time ago (Edge allows them just fine).

**Comment by nero120** [comment]
@olavinto I had no idea Edge did that?! 😭 

It's worse than you think because the idiots at Microsoft remove the duplicate without triggering the [`onRemoved`](https://developer.chrome.com/docs/extensions/reference/bookmarks/#event-onRemoved) API event (thereby breaking the API model), which is why you were seeing errors in xBrowserSync (it doesn't know the bookmarks were removed so doesn't remove them from the map). And people want self-driving cars run on similar quality software! 😖 

I've submitted a support request to the Edge team, I don't hold out much hope of them fixing it any time soon. Sadly this breaks xBrowserSync and will lead to more sync errors so careful...

**Comment by olavinto** [comment]
> @olavinto I had no idea Edge did that?! 😭

🤣

> It's worse than you think because the idiots at Microsoft remove the duplicate without triggering the [`onRemoved`](https://developer.chrome.com/docs/extensions/reference/bookmarks/#event-onRemoved) API event (thereby breaking the API model), which is why you were seeing errors in xBrowserSync (it doesn't know the bookmarks were removed so doesn't remove them from the map). And people want self-driving cars run on similar quality software! 😖
>
> I've submitted a support request to the Edge team, I don't hold out much hope of them fixing it any time soon. Sadly this breaks xBrowserSync and will lead to more sync errors so careful.

Great! Let's hope that they change the way they do things. This is actually also a problem for those who use the native Firefox separators which xBrowserSync converts into simple bookmarks on sync.

> To resolve the issue you would need to remove the duplicates in a different browser synced to the same sync ID, then re-sync in Edge.

Yeah, I did exactly that with Firefox. Fortunately for me it does not actually matter that much that I can't sync from Edge to Firefox since FF is my primary browser. If at these changes start to sync back to Firefox at some point I guess I'll have to stop using those then. You can't have everything.

**Comment by nero120** [comment]
> You can't have everything.

☝️ 😄

**Comment by olavinto** [comment]
The sync does not acgually seem to work on the mobile app (beta 25) although it works with all browsers. Complains about the sync having been updated woth a newer version.

**Comment by nero120** [comment]
@olavinto not sure how that's happening, can you provide me with a list of steps to replicate the issue?

**Comment by olavinto** [comment]
> @olavinto not sure how that's happening, can you provide me with a list of steps to replicate the issue?

Beta 27 fixed this for me, thanks! 🙂👍
