### ISSUE TITLE
Sounds awesome but only bookmarks right?

### ISSUE THREAD

**Issue by nextgenthemes** [xBrowserSync/App#4]
This only syncs bookmarks right?

What about passwords? Is this planned?

I actually only want sync chromium and Firefox on my linux desktop and ended up here. I would trust Mozillas Firefox Sync but its not available for Chrome, someone wanted to implement it and gave up. This sounds even better then Firefox sync, if it would sync passwords as well.

I could even run my own API with node locally right? So I could actually use this for offline syncing my browsers bookmarks?

Anyway looking forward to the Firefox extension.

**Comment by nero120** [comment]
Yes that's right, it only syncs bookmarks currently. The roadmap looks like this:

Mobile apps (iOS and Android, very close to release fixing last few bugs) > Firefox web extension > v1 complete

Once v1 is finished I'll see what the take up is like and depending on popularity start to look at syncing other browser data in v2, such as open tabs, logins/passwords, addresses, etc. The general ethos of the project is to improve productivity of browser-related tasks and accessing bookmarks securely and privately across devices was for me by far the biggest blocker to my productivity, as there was no tool or service that could provide this (from what I could find).

Regarding running your own API locally, absolutely.  Grab the [code](https://github.com/xBrowserSync/API) and follow the install steps in the [readme](https://github.com/xBrowserSync/API/blob/master/README.md) to get up and running. Then simply change the service url in the extension to whatever you've set up on your server to point to the xBrowserSync service and you're good to go.

Thanks for checking out the project and hopefully the Firefox version will be out within a couple of months. :)

**Comment by nextgenthemes** [comment]
@nero120 Thanks. Are you aware of https://arewewebextensionsyet.com/? What are the APIs that are missing for Firefox? I read you say you w8 until Mozilla "finishes" the APIs. Maybe there is no need to wait.

**Comment by nero120** [comment]
Mozilla added support for the web extension apis I need in v52, so it's not
so much about waiting for them it's about how much free time I have! :)

On 23 Apr 2017 01:19, "nextgenthemes" <notifications@github.com> wrote:

@nero120 <https://github.com/nero120> Thanks. Are you aware of
https://arewewebextensionsyet.com/? What are the APIs that are missing for
Firefox? I read you say you w8 until Mozilla "finishes" the APIs. Maybe
there is no need to wait.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/xBrowserSync/App/issues/4#issuecomment-296410303>, or mute
the thread
