### ISSUE TITLE
FireFox Keyword is not supported and gets overwritten.

### ISSUE THREAD

**Issue by Maksym-0xp** [xbrowsersync/app#401]
A clear and concise description of my issue:
Firefox keyword search feature is not supported, thats fair. But xBS removed keywords from saved bookmarks, thats a bug.
keyword is used for creating your own "search engine" that fx lets you search youtube by typing the keyword followed by the search string

1. Create a Bookmark with a keyword
2. sync it
3. notice that the keyword is missing, and will be overwritten locally
4. side note, adding a link that contains %s will result in a warning

Screenshot:
![Untitled](https://user-images.githubusercontent.com/16857670/167360100-d011310f-21ce-4f5d-b0aa-5204dc7fb9be.png)

Using:
Windows 10 x64
Firefox 100.0

Application log:
<details>
<summary>Log entries</summary>
2022-05-09 07:19:58.047	[trace]	Remote bookmarks data updated at 2022-05-09T07:19:56.654Z

2022-05-09 07:20:03.640	[trace]	onCreated event detected

2022-05-09 07:20:04.643	[trace]	Sync xvw2bd (push) queued

2022-05-09 07:20:04.744	[trace]	Sync xvw2bd failed

2022-05-09 07:20:04.751	[error]	bookmarks.sync: [10400] FailedGetPageMetadata

2022-05-09 07:26:26.784	[trace]	Updates available, local:2022-05-09T07:20:04.753Z remote:2022-05-09T07:19:56.654Z
</details>

**Comment by nero120** [comment]
This is a [known issue](https://github.com/xbrowsersync/app/wiki/Known-issues#firefox), when Mozilla pull their fingers out and add tag/keywords to the web extension bookmarks API then xBrowserSync will support them!

**Comment by nero120** [comment]
Apologies, helps if I actually read the issue description!! 😖

**Comment by nero120** [comment]
So now that I've read the issue properly(!), I can confirm the result is unfortunately the same as per tags. Because Mozilla have not added support for adding tags and/or keywords to the web extension bookmarks API, xBrowserSync cannot read or update either of these fields meaning they cannot be synced and thus you will lose them if you use xBrowserSync.

I've added the relevant Mozilla docs links below:

- [`bookmarks.CreateDetails`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/CreateDetails)
- [`bookmarks/update`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/update)

When (if more likely, they are useless at updating the API) Mozilla add this support then I'll be happy to include in xBrowserSync.
