### ISSUE TITLE
Password strength change 1.4.0

### ISSUE THREAD

**Issue by fantawttw** [xbrowsersync/app#42]
Changes have been made to the password algorithm however the user has no way of knowing what you are considering an acceptable password.

### Steps to reproduce
1. Create new sync
2. set password

### Expected behaviour
Able to enter a password of my choosing

### Actual behaviour
Forced password policy with no guidelines.
Just a red, amber green bar showing password strength

### Client app information
**App Platform:** Chrome

**App Platform Version:** 1.4.0

#### Other info
I don't like systems forcing me to use what they consider a strong password.
eg. "thisisaverystrongpasswordandonlyiknowit" is basically unbreakable but it's not allowed.
however "asdasdasdasdasdasd" is allowed.
Please consider removing the complexity requirement that has been added in.

**Comment by nero120** [comment]
Good idea, will look into improving this.

**Comment by fantawttw** [comment]
Perhaps an option to set whether it is a warning or rejection can be added to the server side code.
That way people running their own server side code can make the choice.

**Comment by nero120** [comment]
@hadirena xBrowserSync utilises [angular-complexify](https://github.com/Kraku/angular-complexify) which is an angularjs port of [jquery.complexify.js](https://github.com/danpalmer/jquery.complexify.js). However it looks like jquery.complexify.js is no longer maintained (the website explaining the complexity algorithm is also down) so that's probably a good enough reason to look at replacing this functionality with something else.

[zxcvbn](https://github.com/dropbox/zxcvbn) seems like it could be a good option.

**Comment by nero120** [comment]
@fantawttw I'd like to keep password validation client-side only.

**Comment by fantawttw** [comment]
> @fantawttw I'd like to keep password validation client-side only.

I agree with it being client side, The process I was thinking of would be that the server would respond in the initial /info request or some other mechanism (not sure if this is how your code works) stating rejection type
`{"maxSyncSize":1048576,"message":"server owner message","status":1,"version":"1.1.4","passwordfail":x}`
where passwordfail's x is say 1 reject, or 0 warn.

**Comment by nero120** [comment]
@fantawttw ok I think that's seperate enough to warrant it's own issue so we can track the feature request independently. Could I trouble you to raise a separate issue for this please?
