### ISSUE TITLE
xbrowsersync abandoned?

### ISSUE THREAD

**Issue by fastcat001** [xbrowsersync/app#425]
No updates for very long time.

Has the project been abandoned?

**Comment by nero120** [comment]
Not abandoned as such, I just have no free time currently to work on it, let alone keep up with all the GitHub issues. I maintain the xBrowserSync server so users can still use the service.

**Comment by nero120** [comment]
I hope I will have some time to get v1.6.0 finally released but between my current job and family I literally have no time. I had hoped that some other devs (who know what they are doing) would step forward and help to maintain it but that never happened. It is what it is.

**Comment by paulwratt** [comment]
when you do get a chance to make 1.6.0 public, make the "beta" 1.7.2 public as well (or the version tested for 2 months in the other thread)

**Comment by nero120** [comment]
The 1.7.2 version was a requested feature for a patron but they never responded after I implemented it!

**Comment by nero120** [comment]
Please understand that running an open source project is incredibly demanding and time consuming, especially when you get lots of emails/github issues/requests to manage as well as cutting actual code! I'm not surprised others don't want the responsibility, but it's a shame as it means that projects go stale when the primary maintainer can't commit the time required to the project anymore.

**Comment by nero120** [comment]
I must have put 1000s of hours into this project so don't want it to die so I won't archive it, I'll come back to it when I am able.

**Comment by tbjers** [comment]
> I must have put 1000s of hours into this project so don't want it to die so I won't archive it, I'll come back to it when I am able.

I have been using XBS for a while now and I was wondering if you need help maintaining the project? I am interested, and vested, in the project and would love to augment your current efforts, if you are interested.

**Comment by ivy-reps** [comment]
@nero120, peoples just knows nothing about your project, and they not taking your approach yet. Also from those who are users of your software, not many of them are developers. So it needs time.

**Comment by Forceflow** [comment]
@nero120 Take all the time you need man, we appreciate and understand. The service is alive and working. Take care!

**Comment by drgnfyre** [comment]
> I must have put 1000s of hours into this project so don't want it to die so I won't archive it, I'll come back to it when I am able.

I'm just getting this enabled on all my systems.  Once I've confirmed things are working, I'll have no problems with signing up at the $5 a month tier, or possibly $15

Please consider finding additional people to help with the project.  I'd hate to see it go away.

**Comment by zackmuc** [comment]
can anyone upgrade the manifest to version 3 the old one will soon not work anymore in chrome/ Edge :(

**Comment by rokejulianlockhart** [comment]
@zackmuc, https://github.com/xbrowsersync/app/issues/423

**Comment by ShayBox** [comment]
Please just release v1.7.X, I'm unable to use the latest v1.6.X because I tried the earlier mis-versioned V1.7.X beta so now I have to use the V1.7 beta  
I can't use stable because it's broken, and I can't use the latest v1.6 beta

**Comment by camilus667** [comment]
unfortunately it seems that the plugin is not working anymore https://i.imgur.com/IJEEoKj.jpg
I get this very recurrent error when updating any marker

**Comment by ShayBox** [comment]
I guess the service is dead now too, my sync that's been the same since 2019 and was logged into my browser prior to reinstalling Windows no longer exists... there goes my bookmarks.

**Comment by olavinto** [comment]
> I guess the service is dead now too, my sync that's been the same since 2019 and was logged into my browser prior to reinstalling Windows no longer exists... there goes my bookmarks.

At least for me the sync still works just fine between several browsers. Manifest v3 support (or rather lack of it) will probably be a problem for Chromium based browsers next year as it is my understanding that older addons won't work anymore when it becomes mandatory.

**Comment by elvisisvan** [comment]
i wish i'm programmatically proficient enough to contribute to xbrowsersync, i really hope xbrowsersync can be an ultimate solution to sync bookmarks and browsing history across brave, vivaldi, microsoft edge, etc. different profiles in one single sync id

**Comment by olavinto** [comment]
@nero120 Let me tell you how I feel:

🪦😭💔

**Comment by ivy-reps** [comment]
> To people ending up here like myself: https://github.com/floccusaddon/floccus

I'm not sure that there are privacy here. XBrowserSync is aboiut privacy. And NextCloud, WebDav and etc are not. No encryption.

**Comment by marek22k** [comment]
NextCloud can be encrypted as far as I know.

**Comment by olavinto** [comment]
What cloud service isn't encrypted? NextCloud can also be self hosted. One of the main points of xBrowserSync has been to allow the use of each browser's built in bookmarking features unlike all other choices out there.

**Comment by ivy-reps** [comment]
> NextCloud can be encrypted as far as I know.

I don't think that xbrowsersync encryption approach can be comparable with mostly any service offered around the world. Your bookmarks sent from XBS will be encrypted with your password or whatever and if you will lose it, you will lose ability to decrypt your bookmarks. And they will be sent through channel between browser and the server in encrypted state. As far as I know NextCloud or WebDAV will sent this data in non encrypted way, and if you are provider, you will be able to read that even through HTTPS because now days hardware of provider there will be no problem to "man-in-the-middle" HTTPS channel and boom, especially with very popular services like NextCloud will be no problem to find any data that you has sent.
So if you are want to use NextCloud or whatever feel free.
It's nothing in terms of security and privacy comparingly with xBrowserSync

**Comment by Hr46ph** [comment]
> > To people ending up here like myself: https://github.com/floccusaddon/floccus
> 
> I'm not sure that there are privacy here. XBrowserSync is aboiut privacy. And NextCloud, WebDav and etc are not. No encryption.

haproxy, tls with lets encrypt. webdav backend doesn't matter when internal behind a reverse proxy when its self-hosted. Personally I use encryption at rest for the webdav storage.

Anyone opening services to the public not behind a reverse proxy needs a slap on the hand ;).

I see you talk about security and privacy in other posts as well, think about it this way. If a project is unmaintained, privacy and security  are your first reasons to look elsewhere. You defend this place but its unmaintained. Pointing people to well-maintained alternatives is a good thing. You can keep your head in the sand, doesn't mean others need to.

**Comment by olavinto** [comment]
> > NextCloud can be encrypted as far as I know.
> 
> I don't think that xbrowsersync encryption approach can be comparable with mostly any service offered around the world. Your bookmarks sent from XBS will be encrypted with your password or whatever and if you will lose it, you will lose ability to decrypt your bookmarks. And they will be sent through channel between browser and the server in encrypted state. As far as I know NextCloud or WebDAV will sent this data in non encrypted way, and if you are provider, you will be able to read that even through HTTPS because now days hardware of provider there will be no problem to "man-in-the-middle" HTTPS channel and boom, especially with very popular services like NextCloud will be no problem to find any data that you has sent.
> So if you are want to use NextCloud or whatever feel free.
> It's nothing in terms of security and privacy comparingly with xBrowserSync

As far as I know xBrowserSync does the encryption on the client side and the server only stores encrypted data so it can't be read without your sync ID whichis basically the encryption key. It is end to end encrypted, which is pretty common these days in many cloud services.

**Comment by ivy-reps** [comment]
> > > To people ending up here like myself: https://github.com/floccusaddon/floccus
> > 
> > 
> > I'm not sure that there are privacy here. XBrowserSync is aboiut privacy. And NextCloud, WebDav and etc are not. No encryption.
> 
> haproxy, tls with lets encrypt. webdav backend doesn't matter when internal behind a reverse proxy when its self-hosted. Personally I use encryption at rest for the webdav storage.
> 
> Anyone opening services to the public not behind a reverse proxy needs a slap on the hand ;).
> 
> I see you talk about security and privacy in other posts as well, think about it this way. If a project is unmaintained, privacy and security are your first reasons to look elsewhere. You defend this place but its unmaintained. Pointing people to well-maintained alternatives is a good thing. You can keep your head in the sand, doesn't mean others need to.


I was in a rough state of mind, sadly. Please take my apologies, for previous posts. And please take my apologies for next one messages.

I see you and I see you are trying to make me get your idea rightly. I'm very thankful for sharing project. But please, you or anyone, please, when you are writing about any other XBS like tool, in XBS thread repository, please, write what's the key difference between XBS and others projects that decided to advertise. Better probably will be if you will ask author about that. Key difference is - it's haves nothing with XBS because **XBS bookmarks encrypted from client and it will be encrypted with or without HTTPS layer** and on other project there is no encryption from client side.

Please keep in mind that:
1. https://www.xbrowsersync.org/ is working
2. https://api.xbrowsersync.org/ is working
3. @nero120, just have no time to develop, but project is not dead.
4. Just debug and contribute your fixes here or make a fork and fix it there, may be @nero120 will return and will use fixed or merge your changes.
5. Don't mix non encrypted similar projects which have nothing about encryption like on XBS, at all! That's not fair, and you don't respect authors idea!

Also, Guys if you are thinking that HTTPS protects your data, sadly you just can't imagine how wrong you are. Provider unpacking your data on the fly, real time. Even doesn't not need to analyse packets. Forget about https. I mean if you are speaking in ideology and context of that project, forget about HTTPS at all. Now days hardware and interests to make money from advertisements made HTTPS dead.

**Comment by xkonglong** [comment]
I haven't seen the author for a long time.

**Comment by magicdawn** [comment]
> To people ending up here like myself: [floccusaddon/floccus](https://github.com/floccusaddon/floccus)

this is a good alternative, thanks.

**Comment by iago-pssjd** [comment]
Assuming xbrowsersync is more secure/private than floccus or other alternatives, based on @ivy-reps comment https://github.com/xbrowsersync/app/issues/425#issuecomment-1913646884

Ideally, xbrowsersync would be continued, updated to fix issues and gain compatibility with more browsers and in a future adapted to new (unfortunate) Manifest V3.

Ideally, if @nero120 can't continue with its development, maybe some privacy aware IT company (such as @tutao or @ProtonMail, for example) could take charge of xbrowsersync or develope something similar.

**Comment by swarnat** [comment]
Thanks for reminder. 
I just pushed an update to node.js 22 including major library dependency updates. It is just building.
I think later today I can create the release for updates.

Btw: I used claude.ai to migrate from node-sass to dart sass, whtz can be a pain to do manually. I will try if this can also help us to migrate/update the browser extension. (Because chrome already complain and I'm lost to migrate the angular code to service workers)

**Comment by wuyilingwei** [comment]
One suggestion is to use https://github.com/apps/coderabbitai or similar AI code review, so that you can at least manage pull requests without so much trouble.

**Comment by b0s-at-works** [comment]
@nero120, can you tell why did you stopped to make it? Just because you have no time for that?

Guys, I really don't understand you. If you want that to be fixed, why you can't take it and implement that the way it should be done?
If I understand it rightly, you can create list of tasks or issues to be implemented like it can be done on GitLab for example. Then may be random people will looking at issues and just will fix it or implement it.

Everyone wants to have it done, but no body doing something to support it.

Sadly I'm not JavaScript guy, and no nothing about JavaScript in a sense of browser context. Also I'm not familiar in how it all work in NodeJS, in packaging, compiling. It's just drives me crazy. When we are speaking about PHP or Golang - i'm "pretty not bad", or a bit better then bad, but in js I just don't give a damn.

You can also create discussions, if it's enabled on that project, to discuss with peoples some security concern if you don't know how these procedures have to be (re)implemented securely.

Just offer to do something. To make it right. Take your part. I'm pretty sure that some guys here are JS stuff guys, so you ca review code and to say what can be changed.

Also, do you really think that there are such a bunch of code written to implement that?
It's just a panel with buttons, you are not implementing panel itself. You are implementing client that suppose so exchange with bookmarks with server. That's it. Then also it have to be synced. For me syncing logic the most hard logic.

**Just off top**
For example if you will take syncing between SSD and HDD when you want SSD data always be backuped to HDD, but HDD much slower and you have browse opened which recording to it's dbs something every second pulsing database or web site triggers that? How to store date with guaranty when HDD will always late to store actual data.

So may be something like that can be here when you syncing bookmarks from client and you also need it to have actual everywhere, it can be logically hard to implement, but if few peoples will sit and really sync about that, may be you guys find a way to make it right.

Also, @nero120, may be if you have no time to make it, may be you can set a list of tasks to give it to people, and piece by piece they will implement it?
If you here yet of course.

I really love that extension, and I think this is very important to make it, but anyone who making it should be interested and really love what he has doing.

**Comment by emjayess** [comment]
I "know javascript" (~20 years) and I did recently clone this project and review some of the code. I worked through most of the manifest v3 issues, but there's more to it than just that; there is the matter of migrating/refactoring in the direction of a service worker, and some other aspects of the extension codebase.

This project also leans heavily on Angular, and sports an architectural style that supports building mobile apps in addition to the browser extension from a single codebase... much to its credit, I might add. It is always impressive to pull that off successfully.

But personally, I wouldn't be interested in maintaining all that. I'm not crazy about Angular, and I have no particular desire or need of an android app for my bookmarks. If a fork or replacement were to emerge from this, I'd first stab at the basic browser extension and synching, and forget the mobile app (maybe someone else could maintain that separately, given a documented synching service api). I'd also propose authoring it in vanilla javascript unless or until it proved to be too cumbersome to do so. Then, there may also be an opportunity to reimagine for sustainability of backend storage, and, for example, offering users the option of owning their own data using a cloud storage device (or homelab closet server) of their own choosing. Or maybe even a "web3" decentralized manner of storage. Or maybe just their own private git repository.

**Comment by estomagado** [comment]
> I moved away from xbrowsersync. I would like to delete my data on the https://api.xbrowsersync.org server. I guess there is no such possibility?

I don't think you need to. 
You data is stored encrypted in XBS servers. 
The encryption happened locally in your computer, not in the server, so nobody in the XBS team has the private key to unencrypt it. It is a waste of disk space, yes, but your private and embarrassing bookmarks are safe.

**Comment by tuliogit** [comment]
I cannot see the localization updates despite my language is ready for production. If only one update focused in localization was released...

**Comment by albatros667** [comment]
I'm out completely, I preferred to switch to Raindrop.io, I had to convert all the bookmarks to its format with a script.

[https://i.imgur.com/EMI5Nkp.png](url)

**Comment by JamesClarke7283** [comment]
Ah this isnt great, perhaps i shouldn't store my bookmarks using a browser extension in this way.

My mistake, i now see some glaring issues.

This is assuming all bookmarks stay on the machine. (Which is likely true)

(They could have infra go down, it appears to pick a centralised server, even if you select a different one, i would feel safer(reliability wise) if it was synced to multiple not only 1 *this assuming the encryption is done correctly of course, i assume this is true because there are high level libraries for this*).

If user decided to wipe their machine, didnt back up browser profiles(which i don't backup .local directory) and didnt realise, user would have to pray the server comes back up or they have a recent copy elseware on another device.

This is just a cursory look(~8 minute look), but for my use case of radical reliability (where my bookmarks may not have been backed up elseware), it wont be suitable.

Am going to do the sensible thing and just use Synching or something more generic like a file sync program. (I.E: Not needing custom protocols).

Its a great extension for convenience and privacy, great work guys, ive been using it for years.

Just didnt check if it was suitable for my stringent requirements.

Best wishes (:

James Clarke

**Comment by DawidKrysiak** [comment]
Floccus is HORRIBLE (at least with gdrive as a back-end) - more stress than benefit. is xbrowsersync ever coming back? I did try to write a valid manifest for it so it uploads to chrome... mixed results...

**Comment by olavinto** [comment]
> Floccus is HORRIBLE (at least with gdrive as a back-end) - more stress than benefit. is xbrowsersync ever coming back? I did try to write a valid manifest for it so it uploads to chrome... mixed results... 
What makes it so HORRIBLE? It has worked a long time with very few issues with multiple browsers and on multiple machines, and I'm using Google Drive for sync (that is all I use Google Drive for - not that I'm recommending Google but it works just fine, and other methods are available too). Just set it up once, export your profile and then you can just import it elsewhere (it does require regunfiguring the root folder for some browsers but that could also be avoided by creating separate configs for these).

xBrowserSync was on a fine path but it never really worked without some pretty major issues for a long time (at least not for me whose system and browsers tend to change quite often) and required much more manual steps to setup on a new machine/browser. It also broke my bookmarks file a few times and I had to restore browser backups manually and resef the sync.

**Comment by newbie992** [comment]
Unfortunately xbrowsersync was thrown out in all chrome-based browsers ( my standard-browser is Brave ).
Tried several alternatives, but the best one I found is  bookmarkhub .
It works without any problems .  

Thanks to the developer of xbrowsersync. You did a great job. Your addon was the best until Manifest3 killed it in chrome-based browsers.

**Comment by iagogv3** [comment]
That is a bit off because Brave had claimed they were not going to adopt ManifestV3 (???) (I do not deny your comment, I have also seen the warning regarding this extension)

**Comment by newbie992** [comment]
In the past few months there was only a warning, but xbrowsersync worked as usual.
A few days ago it stopped working completely in Brave ( and chromium as well ). Brave updated to a new version.
Sorry, I forgot to mention that I am using Brave-Beta only because with the stable version of Brave it was impossible to watch Videos on Amazon-Prime-Video channel. In Brave-Beta version it works.

Maybe xbrowsersync still works in the stable version of Brave. I cannot verify this.
Edit: it works in Brave stable.

All Manifest V2 extensions will be deleted in the Chrome Web Store on the last day of August 2026.
https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline

**Comment by DawidKrysiak** [comment]
btw, not sure if I mentioned this, so that's for someone who's just here for "so what do I use now" : I switched to Floccus with gdrive storage for now (s3 was a bit weird - tons of duplicated files, synchronisation issues). I have 4 browsers I need to keep in constant sync, can't afford to wait for the next step of xbrowsersync.
