### ISSUE TITLE
The iOS app can't sync after the release of 1.4.0

### ISSUE THREAD

**Issue by jola16** [xBrowserSync/App#49]
After the release of [1.4.0](https://github.com/xBrowserSync/App/releases/tag/v1.4.0), the iOS app won't  sync. Before reporting the sync issue here, I first tried uninstalling the app (version 1.3.1) and then reinstalling it, **but** then the app couldn't be found at all in the App Store...

Is the 1.4.0 app not available yet in the (swedish) App Store?

Thank you in advance!

**Comment by nero120** [comment]
Hi @jola16, unfortunately, we had to pull the iOS app due to the inability to continue supporting continuous breaking iOS updates from Apple. Not only was this impractical from the goal of having a shared xBrowserSync codebase for all platforms, but it also meant having to purchase newer Apple hardware to develop on as well as paying $99/year for an Apple developer license. Combined with Apple’s extremely stringent App Store submission review process, we couldn't justify the iOS app holding up new releases for the other platforms, so the hard decision was taking to pull iOS support completely. Apologies for the inconvenience. 🙏
