### ISSUE TITLE
Can't start new sync

### ISSUE THREAD

**Issue by FloLaco** [xBrowserSync/App#59]
### Steps to reproduce
1. Instal XBS on Chrome (on Mac)
2. type a password in the password form to create a new sync. The form become red
3. the "next" button can't be clicked

### Expected behaviour
I should go to the next step

### Actual behaviour
I can't click on the "next" button

### Client app information
**App Platform:** Chrome

**App Platform Version:**  1.4.0

#### Other info
<img width="319" alt="capture d ecran 2018-11-25 a 18 23 57" src="https://user-images.githubusercontent.com/1486562/48982254-57baca80-f0e0-11e8-8eed-e4a161df7001.png">

**Comment by nero120** [comment]
The big red bar means you haven't met the password complexity criteria, use a more complex password. #48 addresses making the validation requirements clearer to the user.

**Comment by FloLaco** [comment]
Can you tell me the criteria. I didn't find it. 
And for your info, I tried a very complex password (30 char, capital, special char, but it's still the same)

**Comment by nero120** [comment]
Have a read of [this post](https://github.com/xBrowserSync/App/issues/42#issuecomment-434501444) from #42 as there's some more information there. It allows most complex passwords but if you use common words then it rejects it. The problem is that the source dependency doesn't list the requirements, so unfortunately I can't be any clearer until this issue is resolved, sorry. 🙏
