### ISSUE TITLE
Incomplete sync

### ISSUE THREAD

**Issue by simurq** [xbrowsersync/app#65]
### Steps to reproduce
1. Disable sync on xBrowserSync
2. Export bookmarks to HTML file through Chrome's Bookmarks Manager
3. Delete all local bookmarks from Chrome
4. Import HTML file through Chrome's native Bookmarks Manager
5. Re-enable sync on xBrowserSync

### Expected behaviour
xBrowser should export the imported local bookmarks to the server **in full**, showing sync progress (ticking app icon) and amount of synced data under Data Usage on app's UI (which I guess should be close enough to the size of the backed up HTML file)

### Actual behaviour
Sync starts OK but after 10-20 seconds stops. Data Usage shows about 5-6 KB of data synced, although the size of the HTML is around 230 KB.
Since there is no manual sync button yet (I know it's planned for v1.4.1), I have to disable and re-enable sync to trigger the process. But nothing happens. In fact, the app downloads the previously synced 5 KB of data to the computer and erases local bookmarks. Restarting the browser in order to trigger the app doesn't help either.

### Client app information
**App Platform:** Chrome 
**App Platform Version:** 71.0.3578.98

Thanks!

**Comment by nero120** [comment]
Hi @simurq, apologies for not getting to this sooner. Just to be clear, in step 5 are you creating a new sync or re-syncing to an existing ID?

If you are re-syncing then the local bookmarks will be overwritten with the synced bookmarks. If you are creating a new sync then the local bookmarks will be synced straight to the server. So, the export/import shouldn't make any difference. I've tested both scenarios and I do not experience any issues.

Do you experience this issue when you don't export/import?

**Comment by simurq** [comment]
Hi @nero120, it doesn't matter whether I re-sync to existing ID or create a new sync. I've just tested it before writing this. 
xBrowserSync (xBS) had 95kb of synced data before I deleted all bookmarks. Previously it had >200kb. Now, I decided to do everything from the scratch. With xBS enabled, I first deleted all bookmark folders one after another from my browser watching how xBS also refreshed the server data (0kb of synced data when all local bookmarks were deleted from my rig). So far so good.
Then I imported the backed-up HTML to the existing sync. xBS also refreshed but this time with only 6kB of synced data on the server. When I download this data from the server (Restore function), I can see that many bookmarks are in fact missing.
> Do you experience this issue when you don't export/import?
I'm not sure because, as far as I can see, single bookmarks seem to sync OK, with no issues.

**Comment by nero120** [comment]
I believe the difference in data can be explained by the fact that Chrome does not natively support bookmark descriptions and tags. Therefore, when you export then import your bookmarks via Chrome export/import it will remove all of the descriptions and tags that was stored in your xBrowserSync sync data before the export.

If you are missing bookmarks then this is easily identified by simply enabling your existing sync, this will remove then re-populate all of your local bookmarks as per your synced bookmarks, you can then use Chrome's native bookmark manager to compare how many bookmarks were re-populated compared to what you had before.

Note: make sure you disable sync before using Chrome's import/export to avoid any potential conflicts.

**Comment by simurq** [comment]
> Therefore, when you export then import your bookmarks via Chrome export/import it will remove all of the descriptions and tags that was stored in your xBrowserSync sync data before the export.

That's exactly the opposite - it's xBrowserSync (xBS) that strips the data, not Chrome. I'm not exporting/importing xBS data. It's all about syncing Chrome's HTML bookmarks into xBS server. The pure HTML file exported from Chrome (without descriptions or tags) weighs >200 kb, as I explained in the original post. When xBS tries to sync this data (imported to the browser using Chrome's native import routine), it magically becomes only 5-6 kB on your server.
>If you are missing bookmarks then this is easily identified by simply enabling your existing sync, this will remove then re-populate all of your local bookmarks as per your synced bookmarks...

Yes, after xBS completed syncing, I disabled sync, then deleted all local bookmarks on my browser before re-enabling xBS sync. Now, when xBS restores the freshly synced bookmarks from its server, I can see that many of them, especially the ones stored in various nested folders (!) are missing. That's why I expressed my concern above about the size difference.

**Comment by nero120** [comment]
> That's exactly the opposite - it's xBrowserSync (xBS) that strips the data, not Chrome. I'm not exporting/importing xBS data. It's all about syncing Chrome's HTML bookmarks into xBS server. The pure HTML file exported from Chrome (without descriptions or tags) weighs >200 kb, as I explained in the original post. When xBS tries to sync this data (imported to the browser using Chrome's native import routine), it magically becomes only 5-6 kB on your server.

You said in the first post:

> 1. Disable sync on xBrowserSync
> 2. Export bookmarks to HTML file through Chrome's Bookmarks Manager

So in effect you're just exporting the bookmarks that xBrowserSync already synced, so Chrome will only export bookmark titles and urls, not tags or descriptions. Also, you shouldn't compare the file size of Chrome's exported file with the data usage indicator in xbs as the data size displayed is after compression and encryption, not the plain text bookmarks data you see in the exported chrome html file.

In order to absolutely confirm if there is an issue with xbs syncing, please go through the following steps:

1. Disable sync on xBrowserSync
2. Export bookmarks to HTML file through Chrome's Bookmarks Manager
3. Delete all local bookmarks from Chrome
4. Import HTML file through Chrome's native Bookmarks Manager
5. At this point, take screenshots of your chrome://bookmarks tab to record what's been imported
6. In xBrowserSync, enable debug mode then **create a new sync** (don't sync to an existing ID)
7. Disable, then re-enable syncing with the newly created ID to refresh your local bookmarks
8. Go back to chrome://bookmarks and study the contents for any differences to those in step 5
9. Go to chrome://extensions/, enable developer mode and click on the `background.html` link under xBrowserSync. Go to the Console tab, and if any errors appear in red, right click and "save as..." to save the contents of the Console then please email them to admin@xbrowsersync.org so I can investigate.

Also if at this point you have errors in the console or are seeing bookmarks missing in step 8 that were there in step 5, if you are willing please also email me your chrome backups html file and I will try and recreate the issue.

**Comment by nero120** [comment]
@simurq I've made some major updates to the syncing logic for the upcoming release which I hope will resolve all of your syncing issues. If you can spare a few moments, please give the [v1.5.0 beta release](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta) a try. It would be amazing if you can confirm whether or not it resolves your issues. 🙏

**Comment by nero120** [comment]
@simurq would you mind trying the latest [v1.5.0beta11](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta)?

Please be aware however, due to a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1556427) in Firefox's bookmarks API, changing multiple bookmarks simultaneously will likely result in an error in xBrowserSync. The issues has been fixed in the latest [Firefox Nightly (v69.0a1)](https://www.mozilla.org/en-US/firefox/nightly/all/) so please download and test with Nightly so that you don't hit that known issue.

**Comment by nero120** [comment]
@simurq I've just released v1.5.0 which resolves most syncing issues. Please upgrade and if you're still experiencing the same issues after upgrading comment here.
