### ISSUE TITLE
[Feature request] Import/Export bookmarks with HTML or JSON files

### ISSUE THREAD

**Issue by Primokorn** [xBrowserSync/App#7]
Hi,
Thanks for offering such a useful tool to sync our bookmarks across devices!
I've just installed your app on my Android device and I didnt' find any tool to import bookmarks.

I use Firefox Sync to sync my bookmarks at the moment but I'm looking for a tool to also sync them on my Chromium based browser.
Since I have many bookmarks I'd like to import them into xBrowserSync. Is it something doable?

Thank you.

Note: a way to export bookmarks in HTML or JSON would be appreciated too.

**Comment by nero120** [comment]
Hi @Primokorn! Currently xBrowserSync can sync your Chrome (desktop) bookmarks across your various Chrome browsers (e.g. home pc, work pc, etc) which you can also access on your Android/iOS mobile device using the xBrowserSync app. The reason xBrowserSync has it's own mobile apps rather than simply syncing to the mobile versions of Chrome/Firefox/etc is due to the limitations of accessing mobile browser APIs.

I'm currently in the process of adding support for Firefox desktop for the next release of xBrowserSync. So you could either:

a. Import your Firefox bookmarks to Chrome, install the xBrowserSync Chrome extension and sync your bookmarks, then access them using the xBrowserSync mobile app, but you won't be able to access them on your Firefox desktop browser
or
b. Wait for the next release of xBrowserSync, then install the xBrowserSync Firefox web extension and sync your bookmarks, then access them on your Chrome desktop using the xBrowserSync Chrome extension and on your mobile device with the xBrowserSync mobile app.

You can export your bookmarks in JSON format using the Back Up functionality in the xBrowserSync Chrome extension or mobile apps. Note however, that the JSON structure is specific to xBrowserSync so it will unlikely be interoperable with other tools.

**Comment by nero120** [comment]
Btw thank you for offering to translate xBrowserSync to French! I'll respond to you shortly via email about how we can proceed. :)

**Comment by Primokorn** [comment]
> You can export your bookmarks in JSON format using the Back Up functionality in the xBrowserSync Chrome extension or mobile apps. Note however, that the JSON structure is specific to xBrowserSync so it will unlikely be interoperable with other tools.
As far as I understand, that's a problem. If I stop using your Android app/extensions I'll loose all the bookmarks created with xBrowserSync.
Please correct me if I'm wrong.

No problem for the translations ;)

**Comment by nero120** [comment]
Sorry for the late reply @Primokorn, I missed your response! Don't worry you don't lose any bookmarks if you uninstall or stop using xBrowserSync, this is because it creates native bookmarks in the browser you have installed the web extension for. When you remove the extension, the bookmarks remain and of course you can export them to an html file from Chrome at any point. Hope that clears up your concerns!

**Comment by Primokorn** [comment]
Gotcha. Thanks for your answer.

**Comment by nero120** [comment]
I'm going to close this as Firefox support will be delivered in v1.4.0, re-open if you need anything else.
