### ISSUE TITLE
Bookmark properties fail to be fetched when adding new bookmark in Android

### ISSUE THREAD

**Issue by nakhan98** [xbrowsersync/app#78]
### Steps to reproduce

1. Open a URL in preferred web browser (eg. https://www.xbrowsersync.org/).

2. Attempt to bookmark URL in Xbrowsersync via the android "Share" feature from the web browser. 

3. Wait for browser properties to be fetched as per notification in the Xbrowsersync app.

### Expected behaviour

Browser properties (eg. Title, description) are successfully fetched from webpage at URL and set in the appropriate fields.

### Actual behaviour

The notification "Fetching bookmark properties..." (see screenshots) does not disappear. 

After roughly 10-15 seconds, error message stating "Can't get URL metadata..." (see screenshots) is shown.

### Client app information
**App Platform:** (Chrome, Firefox, iOS, etc)

Android Pi on Huawei.

**App Platform Version:** 

1.4.0

#### Other info

Tried to add URL from latest Brave browser.

Screenshots: https://photos.app.goo.gl/Nvm79sFx2y5sXhVn8

**Comment by nero120** [comment]
@nakhan98 thanks for logging this. Yes this has been an issue for a while due to Cordova's [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) plugin not working correctly. It's supposed to load the bookmark url in the background, execute a script against the loaded page to grab the metdata and then pass it back to xBrowserSync but it has been unreliable recently.

I'm putting the finishing touches to the v1.4.1 chrome/firefox extensions which I'll then release, and then I'll look at updating the android app and hopefully I can get this resolved or find a workaround.
