### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by qazip** [xBrowserSync/App#8]
Hello,

I just tested xBrowserSync on Chrome and what a fantastic service you've here! Congratulations and thank you!

I'd like to be able to use xBrowserSync on firefox. Is there any ETA? Are you already working on it?

**Comment by nero120** [comment]
Hi @qazip, thanks very much and I'm really glad you're enjoying xBrowserSync!

Yes indeed, I'm currently working on Firefox support for the next release (v1.4.0) and am hoping to have it done before the end of the year. :sunglasses:

**Comment by qazip** [comment]
How is this going? Are we close to having a firefox extension?

**Comment by nero120** [comment]
Hi @qazip, still planning on releasing it before the end of Dec, bear with me! :)

**Comment by Primokorn** [comment]
@nero120 Awesome! Despite Quantum, Inox browser is still faster on my computer so I'd like to share my bookmarks between Firefox and Chromium.
Thanks a bunch for this Xmas gift :smiley:

**Comment by qazip** [comment]
Any news? Still on schedule to release until the end of the year?

**Comment by nero120** [comment]
Hi @qazip and Merry Christmas! Unfortunately I've been sidetracked as I've had to focus on a different project for work, but I can assure you I will be focusing on getting the firefox extension for xbrowsersync done once this work is out of the way. Give me a few more weeks and I'll try and have something for you.

Sorry for the delay and thanks for bearing with me!

**Comment by qazip** [comment]
No, thank you! And merry Christhmas to you too!

**Comment by qazip** [comment]
I suppose there is no new information regarding the firefox extension?

**Comment by nero120** [comment]
Hi @qazip, unfortunately I'm afraid not. However I've finally got my free time back and have now begun fixing the current issues raised in the API repo, which won't take long to resolve. Then my focus is 100% on getting this Firefox version out! Sorry it's taken so long, I assure you though, not long to wait now. Thanks for bearing with me, hopefully it will be worth the wait!

**Comment by bernd-wechner** [comment]
It's now Apr 1, Xmarks is shutting down so I'm likely one of a gazillion folk finally motivated to look long and hard at possible replacements. xBrowserSync is on the list, and FOSS ticks a huge box. 

Of course Firefox support is of central interest as I like many I suspect would be interested in keeping a uniform set of browse bookmarks across my instances of Chrome (and Chromium) and Firefox at home, work, on laptop and on mobile (Android) devices if possible. What a dream!

To wit any update on this? 

Needless to say if I end up installing and running with it, I'd fork the code, and keep it on hand for dynamic fixes, which would a dream given how flakey Xmarks became in the past year! 

But, I'm looking I admit at same time at yMarks:

https://www.ymarks.org/

and floccus:

https://github.com/marcelklehr/floccus

and as ever, I admit mildly saddened to see not two but three great starts in seeming competition on solutions for the same problem!

My preference is GitHub (over bitbucket, that ymarks leans on) and life (a living project). All worry me in that space as the xBrowserSync site boldly puts out:

"xBrowserSync is only possible because likeminded individuals contribute their time and skills to support it and make it work."

yet here at github it seems so far there's one contributor. Ditto for ymarks and ditto for floccus. Aaargh.

While I'm capable of changing that and mildly motivated, time poor doesn't begin to describe the state I find myself in, and with paucity of experience in this particular space (which adds a small motivator as I do love learning and gaining skills). 

Part of me is thinking xBrowserSync or Floccus is the best bet, with floccus already supporting Firefox. 

To wit, keen on hearing any  updates from you nero120 and wondering (as I am with the others) how to assess:

1) Which of these three is most advanced
2) Which is most likely to have ongoing life
3) Which has the most receptive single contributor to contributions.

aargh. I'd literally blow $50 buying something like Xmark premium if it saved me these decisions alone I admit. But then FOSS does rock and Xmarks sucked badly for ages now not least because of errors, lousy diagnostics and no way to get action on them or diagnose them oneself and fix!

**Comment by nero120** [comment]
Hey @bernd-wechner! Haha trust me I feel your pain! The lack of what I needed was exactly why I started this project, and because I use it (and will continue to for the foreseeable future) I continue to support and maintain it.

Since I started the user base has grown steadily (with a small explosion recently, I guess thanks to XMarks shutting down as you mention), with zero promotion on my part except for a post or two on reddit to get the word out. As with all FOSS projects, if it continues to grow then other people will be interested in getting involved and the project will grow, I know a few people are running their own xBrowserSync services which is cool. For now I'm just focused on the next updates for the API and for the apps.

My focus is now finally back on xBrowserSync and I'm currently working on the next release for the API, updating it's dependencies and re-jigging the code base into today's tech (things change a lot in a year and a half)! The coding is [done](https://github.com/xBrowserSync/API/tree/v1.1.0), I'm just testing now and cleaning some parts up before I release it and upgrade the current service.

The next commitment is absolutely a firefox version of the web extension, which I had already started writing a few months back but was side tracked by life/work commitments. Really sorry to everyone that it's taking so long, all I can say is please bear with me just a little longer, you'll see commits coming into this repo shortly. As well as firefox support I want to beef up the encryption and add a few enhancements and bug fixes.

Unfortunately I have no experience using yMarks or Floccus so I couldn't comment. I'd be interested to see what people thought regarding your questions though! 😄

**Comment by bernd-wechner** [comment]
Thanks nero120! A great sign of life. I admit I follow this and floccus now on github, ymarks is not on github and seems the least likely candidate, but floccus has been very active and already has extensions:

https://addons.mozilla.org/en-US/firefox/addon/floccus/
https://chrome.google.com/webstore/detail/floccus-nextcloud-sync/behlkinclcpoiijckdfjmibdpnfocefg?hl=en

So a hot contender, though I'd need to install a nextcloud server, which has been on the todo list for a while.  I do like your approach of a standalone server too I admit! For now, sitting and watching until a crunch point I guess, which comes soon when Xmarks goes down.

**Comment by nero120** [comment]
I run my own nextcloud server (as you might imagine) on a Raspberry Pi 3 using the [NextcloudPi](https://github.com/nextcloud/nextcloudpi) build. It's a great build and well supported, so if you do decide to run nextcloud it's a very easy way to get up and running, and I've had no troubles with the RP3. I have had issues with Nextcloud though (which you can follow [here](https://github.com/nextcloud/nextcloudpi/issues/406) if you're interested), though they are not related to nextcloudpi.

I've run my own cloud server since Owncloud and though Nextcloud is much better it still has issues, mainly due to the architecture I think. It's a great project but it does require some time and investment (nextcloudpi helps greatly with this) which is one of the things that stops me working on xBrowserSync! Though I'd take that over giving my private data to a big tech company any day of the week!

**Comment by nachoparker** [comment]
Interesting project here. I will try to look at the alternatives @bernd-wechner mentions and understand the technical differences.

It is great that there is movement, though I aggree that it is "unfortunate" that there is three one person teams competing with each other.

Hopefully cooperation would be possible, but after investing so much I don't see it likely. I guess is the nature of FOSS!

**Comment by nero120** [comment]
Thanks @nachoparker. You know I was thinking the other day that with all the news recently about Facebook it's great that people are becoming more aware that they need to take responsibility for their data, these big tech companies really are a malevolent force that people should be very wary about handing over their data to and supporting.

If the FOSS projects we work on help people to take responsibility for their own data and escape the grip of big tech then that is a noble thing, and I'm happy to dedicate some of my free time to it. In fact, the more options/competition the better, it gives people more choice and means that the ones that work better will gain more usage and more support in the long run, as well they should. Everyone benefits from this, even me if xBrowserSync loses users/support to another project because it's just better, you can bet I'll be using it (and contributing) too! It's a great time to be involved in the FOSS space.

**Comment by ly2314** [comment]
Thank you for developing this nice project!
Since Xmarks is shutting down at May 1, are there any eta for firefox sync extension release?

**Comment by nero120** [comment]
@ly2314 you're very welcome! I've just released a major update to the API so now that's out of the way my next focus is v1.4.0 of the App which will include support for Firefox. I'm aiming to have it released before the end of next month!

**Comment by Rik67** [comment]
Yes, please. There are only a couple of days left.

**Comment by qazip** [comment]
@Rik67, he said "end of next month", which is the end of May, that is, it is a long way out. I wouldn't hold your breath :grinning:

**Comment by nero120** [comment]
I'm going to try and get an alpha build out for you guys asap (via github), with a full release before the end of May.

**Comment by thiagodp** [comment]
@nero120 Is there a branch for that? Maybe people could help you to release it sooner.

**Comment by Primokorn** [comment]
@nero120 Yes please provide your builds on Github ([example](https://github.com/darkreader/darkreader/releases/tag/v3.5.4)).
I don't have access to AMO at work so I'll use it through about:debugging :)

**Comment by nero120** [comment]
@Primokorn you can download the current builds on the [Releases](https://github.com/xBrowserSync/App/releases) page, once I have an Alpha build ready for the firefox version I'll create a (pre-)release for it and reply to this thread.

**Comment by nachoparker** [comment]
I am sure he will announce it when he is ready ;)

**Comment by nero120** [comment]
Just a heads up, unfortunately xbs won't be able to sync tags and descriptions from your native Firefox bookmarks yet as support for reading/writing these properties has not been added to the API yet.

There is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1225916) logged with Mozilla and it looks like it's currently being worked on so hopefully will be ready within the next few months, but obviously not for our initial release.

Still working through some issues on our end, mainly UI which is exhibiting some strange artefacts in Firefox. We're nearly there though, bear with me!

**Comment by nero120** [comment]
Latest update: I've just [committed](https://github.com/xBrowserSync/App/commit/55da55147116e125011b5f38a3986ed52844972d) a number of large firefox sync bug fixes and various other fixes. There are still a few annoying bugs (including some irritating render issues in Firefox) that I need to resolve this week so it's not quite ready, but it's now 95% complete. Thanks for being patient!

I've also realised that this upcoming release will need to be a breaking change in order to properly support syncing firefox bookmarks across the chrome and mobile apps so I'll need to get updated releases ready for those platforms as well to coincide with the firefox release. You'll need to get the latest versions otherwise they won't understand firefox's containers and you won't be able to see your firefox bookmarks! In any case I'll include all the details in the release notes.

I'll update the thread again in a few days! 👨‍💻

**Comment by qazip** [comment]
Great @nero120! I will wait for a release so I can install it on firefox!

**Comment by nero120** [comment]
Latest: Added a major update for v1.4.0 which beefs up the encryption and saves on sync space by ~50% (see this [Patreon post](https://www.patreon.com/posts/19482157) for more details). Should be able to finish off the remaining bugs next week, then I just need to prepare the releases. Very excited about v1.4.0!

**Comment by Metal-Frog** [comment]
When will v1.4.0 be on the release page (including FireFox)?

**Comment by nero120** [comment]
Latest update: Just checked in the final fixes for Firefox syncing which is now code-complete and its syncing beautifully between Firefox and Chrome. As you've all probably guessed, it turned into a bigger job than I expected, I needed to upgrade the security and encryption and I also had to update the API to support having syncs for different versions of the app. Really sorry it's taken so much longer than I had committed to, but I promise it will be worth the wait!

So, I've just got a few minor interface fixes to do (not Firefox specific, but general improvements I want to include with this release) which I'm going to work on this week, then I just need to test there are no showstopping issues with the mobile apps and then I'm going to put an alpha build up on github for you all to check out. As this is a large and complex release I'd really appreciate some feedback before I get the release out into the stores. I'll respond back here with more info soon.

**Comment by qazip** [comment]
Hey @nero120.

Can't you push the extension to AMO? You could create a beta-release if you're not yet comfortable with having the current version in AMO.

**Comment by nero120** [comment]
@qazip I do intend to upload to AMO but I need to get the assets ready, so I won't use it for the beta.

**Comment by nero120** [comment]
Hi everyone, well it's been a mammoth job but v1.4.0 is finally code-complete! I'm currently in the process of testing the browser extensions, and then the mobile versions before I can prepare the full release.

I've created a [beta release](https://github.com/xBrowserSync/App/releases/tag/BETA1) here on GitHub where you can test v1.4.0 on Chrome and Firefox if you're interested in checking it out. I'll repeat the release notes here for your info:

* It is recommended to create a new Chrome/Firefox profile to use for testing this extension.
* The web extension files can be installed by downloading and dragging the appropriate file (.crx=Chrome, .xpi=Firefox) onto the Web Extensions page.
* The beta version is set to use the [api-beta.xbrowsersync.org](https://api-beta.xbrowsersync.org/) service which is intended for testing purposes. Any data synced to this service will not be kept long term.
* The current versions of the extension/mobile apps are not compatible with any sync created with v1.4.0, however you can test sync upgrading by using the current version to create a new sync on [api-beta.xbrowsersync.org](https://api-beta.xbrowsersync.org/), then re-syncing to the generated sync ID using v1.4.0.

If you do find any bugs or issues, please [submit them](https://github.com/xBrowserSync/App/issues/new) and make sure to add `[v1.4.0 BETA]` to the issue title.

There are lots of changes in this release and I haven't prepared full release notes yet, so some things might look a little different but most of the big changes are under the hood and should be transparent for users. If you have any questions feel free to drop them here.

**Comment by osamesama** [comment]
Hey Rich.

Just wanted to say thanks for the work you're doing.  If all I ever used was Chrome, I wouldn't care so much about your work, but I'm really anxious to get some good syncing between Chrome and Firefox, so I'm rooting for you!  To that end, I've just pledged a monthly payment on Patreon.  It's not much, but if everyone who wants Firefox support follows, it could really add up.  Good luck!

To anyone else reading, please consider thanking this guy with your wallet!

**Comment by nero120** [comment]
Thank you very much @osamesama, that's very kind of you! Just to clarify, I didn't start xBrowserSync to make a profit but all of the generous donations on [patreon](https://www.patreon.com/xbrowsersync) go towards the running costs of the api.xbrowsersync.org server, so at least I'm not out of pocket running the service!

I've not found any other issues in my testing between chrome and firefox so things re looking pretty stable. Just need to finish off resolving a few issues with the mobile apps and then v1.4.0 can be released. However, if anyone else would be willing to give the [beta](https://github.com/xBrowserSync/App/releases/tag/BETA1) a try it would definitely help to make sure the release goes smoothly! 🙏

**Comment by matthewdavis** [comment]
With the resolution of #27 I'm content with how the sync happens between the 2 browsers. Finally a proper xmarks replacement!

**Comment by coreagile** [comment]
I installed the Firefox plugin into version 61.0.1 on Pop_OS 18.04, and when I click on the plugin icon to configure it, the window pops up and immediately closes. :-(

Chrome plugin works great!

**Comment by nero120** [comment]
@coreagile that's a strange one! Could you please open a new issue so we can track this and then check the debugging window for errors by:

1. Browsing to `about:debugging#addons` and clicking on `debug` against xBrowserSync
2. Deselect all filters except for "Errors" in the Developer Tools toolbar
2. Click on the ellipses in the top right of the Developer Tools window and select "Disable popup auto-hide"
3. Click on the xBrowserSync icon in the browser window, the window should remain open and any errors that occur should log a message in the Developer Tools Console tab. Copy those error messages into your new issue

Thanks! 😄

**Comment by coreagile** [comment]
Done! https://github.com/xBrowserSync/App/issues/32

**Comment by Metal-Frog** [comment]
@nero120 Where are we right now? :)

**Comment by Primokorn** [comment]
The latest beta works fine with Firefox beta 62. I can't test the sync with another device though.
xbrowsersync automatically merged the current local bookmarks. It could be an option.
Compared to Chromium I just miss a keyboard shortcut to open the extension.

**Comment by crankynet** [comment]
@Primokorn, when you say the latest beta works fine with Firefox beta 62, how is your setup? How many devices do you have Firefox running with xbrowsersync?

**Comment by nero120** [comment]
Hi guys, apologies I've not had much spare time over the past month. Desperate to get this Firefox release out though, will try to make a final push this week/weekend...

**Comment by Primokorn** [comment]
@crankynet It's Firefox beta portable on Windows 7. Since I already use xbrowsersync stable on my other laptop (Chromium) and my phone ST%Iy!&tCgv!iQ2BJHs%^vfn!g!AQ%XmI didn't test the sync.

**Comment by nero120** [comment]
Hi all, I've just resolved a nasty bug affecting syncing on browser startup (#34) so if you're currently using the beta v1.4.0 release grab the latest builds from the [beta release](https://github.com/xBrowserSync/App/releases/tag/BETA1) page.

**Comment by kaphula** [comment]
Hey,

Is it yet possible to sync between Chrome extension and the Firefox beta extension and is the syncing expected to work normally once Firefox extension gets out of beta? Should I just wait for the official release of Firefox extension instead, and if so, is there any rough estimate when the Firefox extension might be available?

Thanks!

**Comment by nero120** [comment]
@kaphula yes it is possible but you need to be running the [v1.4.0 beta](https://github.com/xBrowserSync/App/releases/tag/BETA1) on both Chrome and Firefox. This is really just for testing so if you can wait it's best to wait for the actual release. I've given deadlines for the release before and I always miss them so it's probably best to say that I'm working on it and will release it as soon as I can, I'm expecting that is weeks rather than months.

**Comment by crankynet** [comment]
Does anyone use xbrowsersync 1.4 beta with Firefox on more than 1 PC? Like to hear your experience if you do. Seems like I am not the only one that has issues when running xbrowsersync 1.4 beta with Firefox across 2 Windows 10 PCs. Thanks.

**Comment by nero120** [comment]
Hey all, I've just released a [new version of the beta](https://github.com/xBrowserSync/App/releases/tag/BETA1), this addresses a number of issues experienced by @crankynet and @SpearheadUK when syncing changes between Firefox and Chrome. It also addresses remaining issues with the Android app and includes a few other enhancements (such as use of WOFF2 font files for better performance and bookmark form validation to check if URL has already been bookmarked.

I've also decided to change the mobile app so that you cannot create new syncs from the app, only from the desktop browser extension(s). This is due to a number of people creating a new (empty) sync from the app then syncing their desktop browser to it which of course deletes all of their existing browser bookmarks! Not a great user experience and creating a new sync from the app didn't add a huge amount of value anyway.

Things to do before v1.4.0 is finally released:

- Confirm that the sync issues between Chrome and Firefox have been resolved.
- Test iOS app build.

Thanks for your patience guys, I know it's been a long wait for this update but we're almost there now.

**Comment by coreyfarrell** [comment]
I've just installed the beta on my desktop Firefox.  It appears to work however I don't use Chrome or Chromium and my only other devices are Android.  I don't know how to build Android apps, is it possible to post a beta apk file for manual install?  This would allow me to test synchronization across multiple devices.

About the lack of support for synchronizing Firefox tags, is there any concern this might cause them to be removed from the native bookmarks?  Would xBrowserSync ever delete and recreate the native bookmarks or does it just edit them?  I've used the Firefox native bookmark manager to take a backup so I'm not worried about losing the tags.

**Comment by nero120** [comment]
@coreyfarrell release of v1.4.0 is **imminent** so I'm going to say hold out just a little while longer for that rather than producing more beta builds, though your offering to test is definitely appreciated. In fact, I'm going to close the beta as I think it's served it's purpose, I'll remove the beta release page but I'll leave [api-beta.xbrowsersync.org](https://api-beta.xbrowsersync.org/) up and running until a few weeks after the release of v1.4.0.

> About the lack of support for synchronizing Firefox tags, is there any concern this might cause them to be removed from the native bookmarks?

As Mozilla [have not yet added](https://bugzilla.mozilla.org/show_bug.cgi?id=1448885) support for reading and writing bookmark tags to the Web Extensions bookmarks API, unfortunately yes, any existing native tags will be lost if you use xBrowserSync (local bookmarks are deleted and then re-created when syncing in certain cases). Once they have implemented that part of the API I will incorporate it into xbs.

**Comment by coreyfarrell** [comment]
Thanks for the response.  I'll probably try writing a node.js utility to convert from Firefox native backup (JSON format) into the XBS backup format, that way I can restore the backup that includes my tags.  Even though Firefox will loose the tags XBS will have them.

**Comment by nero120** [comment]
Sweet dude, that would be awesome! In fact, if you're willing to do that would you also be willing to submit a pull request to incorporate the conversion into xbs?

**Comment by hadirena** [comment]
Wah a lot of things happen, keep up the work @nero120

**Comment by coreyfarrell** [comment]
Sorry, I took a look at this and it's not as straight forward as I expected.  Unfortunately I don't have much time to work on open source for the next little while.

**Comment by nero120** [comment]
Ok no worries @coreyfarrell.

**Comment by ly2314** [comment]
I've downloaded v1.4.0 on my Firefox, and it works great :)
Thank you for all the works!

**Comment by nero120** [comment]
Super quick @ly2314! I'm still in the process of rolling out the other versions so if you're using Chrome/Android/iOS you might not get the updates for these until tomorrow.

**Comment by ly2314** [comment]
@nero120 Yep I noticed that too lol

**Comment by rmb938** [comment]
@nero120 Ah thanks for the update, was just about ot make a issue about my password not working in the android app but working in everything else.

**Comment by qazip** [comment]
Can you release this on AMO? (Mozzila's addons page)

**Comment by nero120** [comment]
> Can you release this on AMO? (Mozzila's addons page)

Already done: https://addons.mozilla.org/en-GB/firefox/addon/xbs/

I haven't finished adding the screenshots on the page but you can download it from there.

As is always the case I've found a bug that I want to fix today and once that's done I'll release the Chrome and Android updates. Apple as always are more trouble than they're worth but I don't want the iOS release delaying the rest any further, considering there are much less iOS downloads than on the other platforms. I might even pull it from there completely as it's going to be harder and harder to support in future.

**Comment by coreyfarrell** [comment]
When you publish the Android updates will this include F-DROID?  I thought I could manually install an apk but apparently that's not possible since removed Chrome from my device.

**Comment by nero120** [comment]
> When you publish the Android updates will this include F-DROID? I thought I could manually install an apk but apparently that's not possible since removed Chrome from my device.

Yes, I have my own F-Droid repo here: https://fdroid.xbrowsersync.org/

**Comment by nero120** [comment]
I'll update the F-Droid repo once I release it on the Play Store later today.

**Comment by truncsphere** [comment]
Realized Chrome has been updated yet. Was wondering why my ID/Pass from FF was not working.

**Comment by nero120** [comment]
Hey all, v1.4.0 has now been deployed in the Chrome Web Store and Android Play Store, so you should receive updates shortly. Please note, it looks like the Chrome update doesn't disable the sync after upgrade like it should, so please **disable then re-enable your sync after upgrading to v1.4.0**.

Apple have rejected my submission and I don't think I can resolve the issue due to hardware availability limitations so I want to pull the iOS app but they won't let me pull it in it's current state so it will remain on v1.3.1 until I can figure out how to get it off there... 😠 

@coreyfarrell I didn't get a chance to update and test the f-droid repo today and I'm not going to be able to look at this for a few weeks as my wife is being induced tomorrow and our first son will be born sometime this weekend!! 😱 

I hope you all get on ok with v1.4.0 until I resurface, sorry it took so long to finally release but we got there in the end!!

**Comment by qazip** [comment]
@nero120, thanks for the work and congratulations. Hope everything goes according to plan!

**Comment by coreyfarrell** [comment]
Congrats to you and your wife.

No worries about F-DROID, I just re-enabled Chrome browser temporarily so I could download/install 1.4.0 directly from github.  If you remember I'd appreciate a comment on this issue when F-DROID is updated that way I know when I can re-enable automatic updates.

**Comment by qazip** [comment]
Can someone please try to save a link to a pdf file please.. It gives an error on my end. Just make sure that someone can reproduce so I can open a new issue for that.
