### ISSUE TITLE
Focus Input Search on Open

### ISSUE THREAD

**Issue by bhurler1** [xbrowsersync/app#99]
### Steps to reproduce
1. Click or use shortcut to open extension menu
2. Input not focused
3. Must then click input to type

### Expected behaviour
Please focus the bookmarks search bar when the extension menu is opened or browser shortcut opens it.

### Actual behaviour
Input not focused, requires 2nd click.

### Client app information
**App Platform:** (Chrome, Firefox, etc) 
Brave/Chrome

**App Platform Version:** 

#### Other info
```
Enter any other information you think would be helpful here.
```

**Comment by nero120** [comment]
This is already implemented, can you be more specific about your platform and browser version please?

**Comment by bhurler1** [comment]
Apologies, I am using Brave Version 0.64.77 Chromium: 74.0.3729.169 (Official Build) (64-bit)

**Comment by nero120** [comment]
Ah ok. Brave is not currently supported so even though it has some support for Chrome extensions there may be issues as describe.

I'm going to close this issue but could you please open a separate issue to request support for Brave so that users can upvote it if they'd also like xBrowserSync to support it? Thanks!

**Comment by bhurler1** [comment]
Absolutely. Thank you!
